[package]
name = "onnx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
protobuf = "3.2.0"
ndarray = "0.15.3"
num-traits = "0.2"
ndarray-npy = "0.8.1"